apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-operator
  namespace: openshift-csi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-operator
  template:
    metadata:
      labels:
        name: csi-operator
    spec:
      serviceAccount: csi-operator
      containers:
        - name: csi-operator
          image: registry.svc.ci.openshift.org/openshift/origin-v4.0:csi-operator
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "ovirt-csi-operator"
          args:
            - "--config=/etc/ovirt-csi-operator/config.yaml"
            - "--v=5"
          volumeMounts:
            - name: configuration
              mountPath: /etc/csi-operator/
      volumes:
        - name: configuration
          configMap:
            name: csi-operator-config
